<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Evently.Application\Evently.Application.csproj" />
    <ProjectReference Include="..\Evently.Domain\Evently.Domain.csproj" />
  </ItemGroup>

</Project>
